apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust
  labels:
    app: rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust
  template:
    metadata:
      labels:
        app: rust
    spec:
      containers:
      - name: rust
        image: ghcr.io/${IMAGE_NAME}:main
        imagePullPolicy: Always
        resources:
          requests:
            cpu: ".1"
            memory: ".1Gi"
          limits:
            cpu: ".1"
            memory: ".1Gi"
        ports:
        - containerPort: 8080
